version: '3.8'

services:
    local:
        container_name: todo-kourosh
        image: todo-kourosh:1.0.0
        build:
            context: .
            target: local
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
        environment:
            NODE_ENV: local
            DB_PORT: 3306
            DB_USERNAME: root
            DB_PASSWORD: ilovealphapod
            DB_DATABASE: todo
            DB_HOST: host.docker.internal
        links:
            - mysql
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped


    mysql:
        platform: linux/x86_64
        container_name: mysqldb
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: "todo"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "ilovealphapod"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306"


networks:
    nesjs-network:
